[project]
name = "vggt-pretraining"
version = "0.1.0"
description = "Testing out VGGT inspired models for understanding dynamic scenes efficiently"
requires-python = ">=3.14"
dependencies = [
    "gsplat>=1.5.3",
    "huggingface-hub>=1.19.0",
    "packaging>=26.2",
    "plyfile>=1.1.4",
    "scikit-learn>=1.9.0",
]
