#!/bin/bash
# Regenerate Python protobuf files from .proto definitions.
# Run this from the project root or proto/ directory whenever proto files change.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Use grpcio-tools if available, otherwise fall back to protoc directly
if python -c "import grpc_tools" 2>/dev/null; then
    python -m grpc_tools.protoc \
        -I. \
        --python_out=. \
        primitives.proto perceiver.proto spatial.proto segmentation.proto
else
    protoc \
        -I. \
        --python_out=. \
        primitives.proto perceiver.proto spatial.proto segmentation.proto
fi

# Regenerate __init__.py
cat > __init__.py << 'EOF'
# Auto-generated by generate_proto.sh
from . import primitives_pb2
from . import perceiver_pb2
from . import spatial_pb2
from . import segmentation_pb2
EOF

echo "Proto files generated successfully."
